spring:
  application:
    name: cloud-native-spring
  main:
    allow-bean-definition-overriding: true
  profiles.active: dev

server.port: 8080


management:
  endpoints:
    web:
      exposure:
        include: '*'


cook.special: "Kim Chi in cloud-native-spring app"